# baseURL = "http://example.org/"
languageCode = "en-us"
title = "what is..."
theme = "ananke"
logo = "logo.png"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/noopsJapan"
  github = "https://github.com/noopsjapan"
  background_color_class = "bg-dark-blue"
  featured_image = "./groupphoto.jpg"
  recent_posts_number = 2
  custom_css = ["site.css"]

[languages]
    [languages.en]
        title="NoOps Japan"
    [languages.ja]
        title="NoOps Japan"
[languages.ja.menu]
    [[languages.ja.menu.main]]
        identifier = "Home"
        name = "ホーム"
        url = "/ja/"
        weight = -110
    [[languages.ja.menu.main]]
      name = "Code of Conduct"
      url = ""
      weight = -80
    [[languages.ja.menu.main]]
      name = "NoOpsとは？"
      url = "/ja/definition/"
      weight = -90

[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = -110

  [[menu.main]]
    name = "Code of Conduct"
    url = "/codeofconduct/"
    weight = -80

  [[menu.main]]
    name = "Definition"
    url = "/definition/"
    weight = -90