name: CI

on: 
  push:
    branches: 
      - release

jobs:
  build-deploy:
    runs-on: ubuntu-18.04   
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.1
      with:
        hugo-version: '0.58.3'

    - name: Build
      run: hugo --gc --minify --cleanDestinationDir
    
    - name: Deploy
      uses: noopsjapan/noopsjapan.github.io
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
